DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40),
    email varchar(50)
);

CREATE TABLE items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40) NOT NULL,
    description varchar(120) NOT NULL,
    owner INTEGER NOT NULL,
    available boolean DEFAULT FALSE,
    FOREIGN KEY (owner) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE bookings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id INTEGER NOT NULL,
    booker_id INTEGER NOT NULL,
    start_booking TIMESTAMP NOT NULL,
    end_booking TIMESTAMP NOT NULL,
    state varchar(40) DEFAULT 'WAITING',
    FOREIGN KEY (booker_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
);

CREATE TABLE comments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_of_comment_id INTEGER NOT NULL,
    item_id INTEGER NOT NULL,
    author_name varchar(128),
    text varchar(500),
    created TIMESTAMP,
    FOREIGN KEY (owner_of_comment_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
);