# -----------------------------------
# Server
# -----------------------------------
server.port=9090

# -----------------------------------
# JPA / Hibernate
# -----------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=never

# -----------------------------------
# DataSource (PostgreSQL in Docker)
# -----------------------------------
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/shareit}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:shareit}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:shareit}
spring.datasource.driver-class-name=org.postgresql.Driver

# -----------------------------------
# Logging
# -----------------------------------
logging.level.org.springframework.orm.jpa=INFO
logging.level.org.springframework.transaction=INFO
logging.level.org.springframework.transaction.interceptor=TRACE
logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG