DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS responses;
DROP TABLE IF EXISTS requests;

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40),
    email varchar(50)
);

CREATE TABLE requests(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description varchar(128),
    requester_id INTEGER,
    time_of_create TIMESTAMP,
    --FOREIGN KEY (response_id) REFERENCES responses(id),
    FOREIGN KEY (requester_id) REFERENCES users(id)
);

CREATE TABLE items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40) NOT NULL,
    description varchar(120) NOT NULL,
    owner INTEGER NOT NULL,
    request_id INTEGER DEFAULT NULL,
    available boolean DEFAULT FALSE,
    FOREIGN KEY (owner) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (request_id) REFERENCES requests(id)
);
CREATE TABLE responses(
    id INTEGER,
    user_id INTEGER,
    item_id INTEGER,
    item_name varchar(40),
    item_request_id INTEGER,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (item_id) REFERENCES items(id),
    FOREIGN KEY (item_request_id) REFERENCES requests(id)
);

CREATE TABLE bookings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id INTEGER NOT NULL,
    booker_id INTEGER NOT NULL,
    start_booking TIMESTAMP NOT NULL,
    end_booking TIMESTAMP NOT NULL,
    state varchar(40) DEFAULT 'WAITING',
    FOREIGN KEY (booker_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
);

CREATE TABLE comments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_of_comment_id INTEGER NOT NULL,
    item_id INTEGER NOT NULL,
    author_name varchar(128),
    text varchar(500),
    created TIMESTAMP,
    FOREIGN KEY (owner_of_comment_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
);